/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StafRouteImport } from './routes/staf'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DaftarStaffRouteImport } from './routes/daftar-staff'
import { Route as DaftarAnakRouteImport } from './routes/daftar-anak'
import { Route as AnakRouteImport } from './routes/anak'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StafIndexRouteImport } from './routes/staf.index'
import { Route as AnakIndexRouteImport } from './routes/anak.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StafWargaEmasRouteImport } from './routes/staf.warga-emas'
import { Route as AnakServiceRouteImport } from './routes/anak.service'
import { Route as AnakDaftarWargaRouteImport } from './routes/anak.daftar-warga'
import { Route as AdminVideoRouteImport } from './routes/admin.video'
import { Route as AdminTrackerRouteImport } from './routes/admin.tracker'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminServisRouteImport } from './routes/admin.servis'
import { Route as AdminArtikelRouteImport } from './routes/admin.artikel'
import { Route as StafRekodIndexRouteImport } from './routes/staf.rekod.index'
import { Route as AnakPerkembanganIndexRouteImport } from './routes/anak.perkembangan.index'
import { Route as AnakInformasiIndexRouteImport } from './routes/anak.informasi.index'
import { Route as AdminWargaEmasIndexRouteImport } from './routes/admin.warga-emas.index'
import { Route as StafRekodParentIdRouteImport } from './routes/staf.rekod.$parentId'
import { Route as AnakPerkembanganParentIdRouteImport } from './routes/anak.perkembangan.$parentId'
import { Route as AnakInformasiIdRouteImport } from './routes/anak.informasi.$id'
import { Route as AdminWargaEmasBaruRouteImport } from './routes/admin.warga-emas.baru'
import { Route as AdminWargaEmasParentIdRouteImport } from './routes/admin.warga-emas.$parentId'
import { Route as AdminRekodPenjagaanBookingIdRouteImport } from './routes/admin.rekod-penjagaan.$bookingId'
import { Route as AdminRekodHarianRecordIdRouteImport } from './routes/admin.rekod-harian.$recordId'
import { Route as StafTrackerParentIdIndexRouteImport } from './routes/staf.tracker.$parentId.index'
import { Route as StafTrackerParentIdVitalRouteImport } from './routes/staf.tracker.$parentId.vital'
import { Route as StafTrackerParentIdUbatRouteImport } from './routes/staf.tracker.$parentId.ubat'
import { Route as StafTrackerParentIdMakananRouteImport } from './routes/staf.tracker.$parentId.makanan'
import { Route as StafTrackerParentIdAktivitiRouteImport } from './routes/staf.tracker.$parentId.aktiviti'
import { Route as StafTrackerParentIdSejarahRecordIdRouteImport } from './routes/staf.tracker.$parentId.sejarah.$recordId'

const StafRoute = StafRouteImport.update({
  id: '/staf',
  path: '/staf',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarStaffRoute = DaftarStaffRouteImport.update({
  id: '/daftar-staff',
  path: '/daftar-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarAnakRoute = DaftarAnakRouteImport.update({
  id: '/daftar-anak',
  path: '/daftar-anak',
  getParentRoute: () => rootRouteImport,
} as any)
const AnakRoute = AnakRouteImport.update({
  id: '/anak',
  path: '/anak',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StafIndexRoute = StafIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StafRoute,
} as any)
const AnakIndexRoute = AnakIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnakRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StafWargaEmasRoute = StafWargaEmasRouteImport.update({
  id: '/warga-emas',
  path: '/warga-emas',
  getParentRoute: () => StafRoute,
} as any)
const AnakServiceRoute = AnakServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AnakRoute,
} as any)
const AnakDaftarWargaRoute = AnakDaftarWargaRouteImport.update({
  id: '/daftar-warga',
  path: '/daftar-warga',
  getParentRoute: () => AnakRoute,
} as any)
const AdminVideoRoute = AdminVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackerRoute = AdminTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServisRoute = AdminServisRouteImport.update({
  id: '/servis',
  path: '/servis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtikelRoute = AdminArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => AdminRoute,
} as any)
const StafRekodIndexRoute = StafRekodIndexRouteImport.update({
  id: '/rekod/',
  path: '/rekod/',
  getParentRoute: () => StafRoute,
} as any)
const AnakPerkembanganIndexRoute = AnakPerkembanganIndexRouteImport.update({
  id: '/perkembangan/',
  path: '/perkembangan/',
  getParentRoute: () => AnakRoute,
} as any)
const AnakInformasiIndexRoute = AnakInformasiIndexRouteImport.update({
  id: '/informasi/',
  path: '/informasi/',
  getParentRoute: () => AnakRoute,
} as any)
const AdminWargaEmasIndexRoute = AdminWargaEmasIndexRouteImport.update({
  id: '/warga-emas/',
  path: '/warga-emas/',
  getParentRoute: () => AdminRoute,
} as any)
const StafRekodParentIdRoute = StafRekodParentIdRouteImport.update({
  id: '/rekod/$parentId',
  path: '/rekod/$parentId',
  getParentRoute: () => StafRoute,
} as any)
const AnakPerkembanganParentIdRoute =
  AnakPerkembanganParentIdRouteImport.update({
    id: '/perkembangan/$parentId',
    path: '/perkembangan/$parentId',
    getParentRoute: () => AnakRoute,
  } as any)
const AnakInformasiIdRoute = AnakInformasiIdRouteImport.update({
  id: '/informasi/$id',
  path: '/informasi/$id',
  getParentRoute: () => AnakRoute,
} as any)
const AdminWargaEmasBaruRoute = AdminWargaEmasBaruRouteImport.update({
  id: '/warga-emas/baru',
  path: '/warga-emas/baru',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWargaEmasParentIdRoute = AdminWargaEmasParentIdRouteImport.update({
  id: '/warga-emas/$parentId',
  path: '/warga-emas/$parentId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRekodPenjagaanBookingIdRoute =
  AdminRekodPenjagaanBookingIdRouteImport.update({
    id: '/rekod-penjagaan/$bookingId',
    path: '/rekod-penjagaan/$bookingId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRekodHarianRecordIdRoute =
  AdminRekodHarianRecordIdRouteImport.update({
    id: '/rekod-harian/$recordId',
    path: '/rekod-harian/$recordId',
    getParentRoute: () => AdminRoute,
  } as any)
const StafTrackerParentIdIndexRoute =
  StafTrackerParentIdIndexRouteImport.update({
    id: '/tracker/$parentId/',
    path: '/tracker/$parentId/',
    getParentRoute: () => StafRoute,
  } as any)
const StafTrackerParentIdVitalRoute =
  StafTrackerParentIdVitalRouteImport.update({
    id: '/tracker/$parentId/vital',
    path: '/tracker/$parentId/vital',
    getParentRoute: () => StafRoute,
  } as any)
const StafTrackerParentIdUbatRoute = StafTrackerParentIdUbatRouteImport.update({
  id: '/tracker/$parentId/ubat',
  path: '/tracker/$parentId/ubat',
  getParentRoute: () => StafRoute,
} as any)
const StafTrackerParentIdMakananRoute =
  StafTrackerParentIdMakananRouteImport.update({
    id: '/tracker/$parentId/makanan',
    path: '/tracker/$parentId/makanan',
    getParentRoute: () => StafRoute,
  } as any)
const StafTrackerParentIdAktivitiRoute =
  StafTrackerParentIdAktivitiRouteImport.update({
    id: '/tracker/$parentId/aktiviti',
    path: '/tracker/$parentId/aktiviti',
    getParentRoute: () => StafRoute,
  } as any)
const StafTrackerParentIdSejarahRecordIdRoute =
  StafTrackerParentIdSejarahRecordIdRouteImport.update({
    id: '/tracker/$parentId/sejarah/$recordId',
    path: '/tracker/$parentId/sejarah/$recordId',
    getParentRoute: () => StafRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anak': typeof AnakRouteWithChildren
  '/daftar-anak': typeof DaftarAnakRoute
  '/daftar-staff': typeof DaftarStaffRoute
  '/login': typeof LoginRoute
  '/staf': typeof StafRouteWithChildren
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/servis': typeof AdminServisRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tracker': typeof AdminTrackerRoute
  '/admin/video': typeof AdminVideoRoute
  '/anak/daftar-warga': typeof AnakDaftarWargaRoute
  '/anak/service': typeof AnakServiceRoute
  '/staf/warga-emas': typeof StafWargaEmasRoute
  '/admin/': typeof AdminIndexRoute
  '/anak/': typeof AnakIndexRoute
  '/staf/': typeof StafIndexRoute
  '/admin/rekod-harian/$recordId': typeof AdminRekodHarianRecordIdRoute
  '/admin/rekod-penjagaan/$bookingId': typeof AdminRekodPenjagaanBookingIdRoute
  '/admin/warga-emas/$parentId': typeof AdminWargaEmasParentIdRoute
  '/admin/warga-emas/baru': typeof AdminWargaEmasBaruRoute
  '/anak/informasi/$id': typeof AnakInformasiIdRoute
  '/anak/perkembangan/$parentId': typeof AnakPerkembanganParentIdRoute
  '/staf/rekod/$parentId': typeof StafRekodParentIdRoute
  '/admin/warga-emas/': typeof AdminWargaEmasIndexRoute
  '/anak/informasi/': typeof AnakInformasiIndexRoute
  '/anak/perkembangan/': typeof AnakPerkembanganIndexRoute
  '/staf/rekod/': typeof StafRekodIndexRoute
  '/staf/tracker/$parentId/aktiviti': typeof StafTrackerParentIdAktivitiRoute
  '/staf/tracker/$parentId/makanan': typeof StafTrackerParentIdMakananRoute
  '/staf/tracker/$parentId/ubat': typeof StafTrackerParentIdUbatRoute
  '/staf/tracker/$parentId/vital': typeof StafTrackerParentIdVitalRoute
  '/staf/tracker/$parentId/': typeof StafTrackerParentIdIndexRoute
  '/staf/tracker/$parentId/sejarah/$recordId': typeof StafTrackerParentIdSejarahRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar-anak': typeof DaftarAnakRoute
  '/daftar-staff': typeof DaftarStaffRoute
  '/login': typeof LoginRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/servis': typeof AdminServisRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tracker': typeof AdminTrackerRoute
  '/admin/video': typeof AdminVideoRoute
  '/anak/daftar-warga': typeof AnakDaftarWargaRoute
  '/anak/service': typeof AnakServiceRoute
  '/staf/warga-emas': typeof StafWargaEmasRoute
  '/admin': typeof AdminIndexRoute
  '/anak': typeof AnakIndexRoute
  '/staf': typeof StafIndexRoute
  '/admin/rekod-harian/$recordId': typeof AdminRekodHarianRecordIdRoute
  '/admin/rekod-penjagaan/$bookingId': typeof AdminRekodPenjagaanBookingIdRoute
  '/admin/warga-emas/$parentId': typeof AdminWargaEmasParentIdRoute
  '/admin/warga-emas/baru': typeof AdminWargaEmasBaruRoute
  '/anak/informasi/$id': typeof AnakInformasiIdRoute
  '/anak/perkembangan/$parentId': typeof AnakPerkembanganParentIdRoute
  '/staf/rekod/$parentId': typeof StafRekodParentIdRoute
  '/admin/warga-emas': typeof AdminWargaEmasIndexRoute
  '/anak/informasi': typeof AnakInformasiIndexRoute
  '/anak/perkembangan': typeof AnakPerkembanganIndexRoute
  '/staf/rekod': typeof StafRekodIndexRoute
  '/staf/tracker/$parentId/aktiviti': typeof StafTrackerParentIdAktivitiRoute
  '/staf/tracker/$parentId/makanan': typeof StafTrackerParentIdMakananRoute
  '/staf/tracker/$parentId/ubat': typeof StafTrackerParentIdUbatRoute
  '/staf/tracker/$parentId/vital': typeof StafTrackerParentIdVitalRoute
  '/staf/tracker/$parentId': typeof StafTrackerParentIdIndexRoute
  '/staf/tracker/$parentId/sejarah/$recordId': typeof StafTrackerParentIdSejarahRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anak': typeof AnakRouteWithChildren
  '/daftar-anak': typeof DaftarAnakRoute
  '/daftar-staff': typeof DaftarStaffRoute
  '/login': typeof LoginRoute
  '/staf': typeof StafRouteWithChildren
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/servis': typeof AdminServisRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tracker': typeof AdminTrackerRoute
  '/admin/video': typeof AdminVideoRoute
  '/anak/daftar-warga': typeof AnakDaftarWargaRoute
  '/anak/service': typeof AnakServiceRoute
  '/staf/warga-emas': typeof StafWargaEmasRoute
  '/admin/': typeof AdminIndexRoute
  '/anak/': typeof AnakIndexRoute
  '/staf/': typeof StafIndexRoute
  '/admin/rekod-harian/$recordId': typeof AdminRekodHarianRecordIdRoute
  '/admin/rekod-penjagaan/$bookingId': typeof AdminRekodPenjagaanBookingIdRoute
  '/admin/warga-emas/$parentId': typeof AdminWargaEmasParentIdRoute
  '/admin/warga-emas/baru': typeof AdminWargaEmasBaruRoute
  '/anak/informasi/$id': typeof AnakInformasiIdRoute
  '/anak/perkembangan/$parentId': typeof AnakPerkembanganParentIdRoute
  '/staf/rekod/$parentId': typeof StafRekodParentIdRoute
  '/admin/warga-emas/': typeof AdminWargaEmasIndexRoute
  '/anak/informasi/': typeof AnakInformasiIndexRoute
  '/anak/perkembangan/': typeof AnakPerkembanganIndexRoute
  '/staf/rekod/': typeof StafRekodIndexRoute
  '/staf/tracker/$parentId/aktiviti': typeof StafTrackerParentIdAktivitiRoute
  '/staf/tracker/$parentId/makanan': typeof StafTrackerParentIdMakananRoute
  '/staf/tracker/$parentId/ubat': typeof StafTrackerParentIdUbatRoute
  '/staf/tracker/$parentId/vital': typeof StafTrackerParentIdVitalRoute
  '/staf/tracker/$parentId/': typeof StafTrackerParentIdIndexRoute
  '/staf/tracker/$parentId/sejarah/$recordId': typeof StafTrackerParentIdSejarahRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anak'
    | '/daftar-anak'
    | '/daftar-staff'
    | '/login'
    | '/staf'
    | '/admin/artikel'
    | '/admin/servis'
    | '/admin/staff'
    | '/admin/tracker'
    | '/admin/video'
    | '/anak/daftar-warga'
    | '/anak/service'
    | '/staf/warga-emas'
    | '/admin/'
    | '/anak/'
    | '/staf/'
    | '/admin/rekod-harian/$recordId'
    | '/admin/rekod-penjagaan/$bookingId'
    | '/admin/warga-emas/$parentId'
    | '/admin/warga-emas/baru'
    | '/anak/informasi/$id'
    | '/anak/perkembangan/$parentId'
    | '/staf/rekod/$parentId'
    | '/admin/warga-emas/'
    | '/anak/informasi/'
    | '/anak/perkembangan/'
    | '/staf/rekod/'
    | '/staf/tracker/$parentId/aktiviti'
    | '/staf/tracker/$parentId/makanan'
    | '/staf/tracker/$parentId/ubat'
    | '/staf/tracker/$parentId/vital'
    | '/staf/tracker/$parentId/'
    | '/staf/tracker/$parentId/sejarah/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar-anak'
    | '/daftar-staff'
    | '/login'
    | '/admin/artikel'
    | '/admin/servis'
    | '/admin/staff'
    | '/admin/tracker'
    | '/admin/video'
    | '/anak/daftar-warga'
    | '/anak/service'
    | '/staf/warga-emas'
    | '/admin'
    | '/anak'
    | '/staf'
    | '/admin/rekod-harian/$recordId'
    | '/admin/rekod-penjagaan/$bookingId'
    | '/admin/warga-emas/$parentId'
    | '/admin/warga-emas/baru'
    | '/anak/informasi/$id'
    | '/anak/perkembangan/$parentId'
    | '/staf/rekod/$parentId'
    | '/admin/warga-emas'
    | '/anak/informasi'
    | '/anak/perkembangan'
    | '/staf/rekod'
    | '/staf/tracker/$parentId/aktiviti'
    | '/staf/tracker/$parentId/makanan'
    | '/staf/tracker/$parentId/ubat'
    | '/staf/tracker/$parentId/vital'
    | '/staf/tracker/$parentId'
    | '/staf/tracker/$parentId/sejarah/$recordId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anak'
    | '/daftar-anak'
    | '/daftar-staff'
    | '/login'
    | '/staf'
    | '/admin/artikel'
    | '/admin/servis'
    | '/admin/staff'
    | '/admin/tracker'
    | '/admin/video'
    | '/anak/daftar-warga'
    | '/anak/service'
    | '/staf/warga-emas'
    | '/admin/'
    | '/anak/'
    | '/staf/'
    | '/admin/rekod-harian/$recordId'
    | '/admin/rekod-penjagaan/$bookingId'
    | '/admin/warga-emas/$parentId'
    | '/admin/warga-emas/baru'
    | '/anak/informasi/$id'
    | '/anak/perkembangan/$parentId'
    | '/staf/rekod/$parentId'
    | '/admin/warga-emas/'
    | '/anak/informasi/'
    | '/anak/perkembangan/'
    | '/staf/rekod/'
    | '/staf/tracker/$parentId/aktiviti'
    | '/staf/tracker/$parentId/makanan'
    | '/staf/tracker/$parentId/ubat'
    | '/staf/tracker/$parentId/vital'
    | '/staf/tracker/$parentId/'
    | '/staf/tracker/$parentId/sejarah/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnakRoute: typeof AnakRouteWithChildren
  DaftarAnakRoute: typeof DaftarAnakRoute
  DaftarStaffRoute: typeof DaftarStaffRoute
  LoginRoute: typeof LoginRoute
  StafRoute: typeof StafRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staf': {
      id: '/staf'
      path: '/staf'
      fullPath: '/staf'
      preLoaderRoute: typeof StafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-staff': {
      id: '/daftar-staff'
      path: '/daftar-staff'
      fullPath: '/daftar-staff'
      preLoaderRoute: typeof DaftarStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-anak': {
      id: '/daftar-anak'
      path: '/daftar-anak'
      fullPath: '/daftar-anak'
      preLoaderRoute: typeof DaftarAnakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anak': {
      id: '/anak'
      path: '/anak'
      fullPath: '/anak'
      preLoaderRoute: typeof AnakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staf/': {
      id: '/staf/'
      path: '/'
      fullPath: '/staf/'
      preLoaderRoute: typeof StafIndexRouteImport
      parentRoute: typeof StafRoute
    }
    '/anak/': {
      id: '/anak/'
      path: '/'
      fullPath: '/anak/'
      preLoaderRoute: typeof AnakIndexRouteImport
      parentRoute: typeof AnakRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staf/warga-emas': {
      id: '/staf/warga-emas'
      path: '/warga-emas'
      fullPath: '/staf/warga-emas'
      preLoaderRoute: typeof StafWargaEmasRouteImport
      parentRoute: typeof StafRoute
    }
    '/anak/service': {
      id: '/anak/service'
      path: '/service'
      fullPath: '/anak/service'
      preLoaderRoute: typeof AnakServiceRouteImport
      parentRoute: typeof AnakRoute
    }
    '/anak/daftar-warga': {
      id: '/anak/daftar-warga'
      path: '/daftar-warga'
      fullPath: '/anak/daftar-warga'
      preLoaderRoute: typeof AnakDaftarWargaRouteImport
      parentRoute: typeof AnakRoute
    }
    '/admin/video': {
      id: '/admin/video'
      path: '/video'
      fullPath: '/admin/video'
      preLoaderRoute: typeof AdminVideoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracker': {
      id: '/admin/tracker'
      path: '/tracker'
      fullPath: '/admin/tracker'
      preLoaderRoute: typeof AdminTrackerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servis': {
      id: '/admin/servis'
      path: '/servis'
      fullPath: '/admin/servis'
      preLoaderRoute: typeof AdminServisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artikel': {
      id: '/admin/artikel'
      path: '/artikel'
      fullPath: '/admin/artikel'
      preLoaderRoute: typeof AdminArtikelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staf/rekod/': {
      id: '/staf/rekod/'
      path: '/rekod'
      fullPath: '/staf/rekod/'
      preLoaderRoute: typeof StafRekodIndexRouteImport
      parentRoute: typeof StafRoute
    }
    '/anak/perkembangan/': {
      id: '/anak/perkembangan/'
      path: '/perkembangan'
      fullPath: '/anak/perkembangan/'
      preLoaderRoute: typeof AnakPerkembanganIndexRouteImport
      parentRoute: typeof AnakRoute
    }
    '/anak/informasi/': {
      id: '/anak/informasi/'
      path: '/informasi'
      fullPath: '/anak/informasi/'
      preLoaderRoute: typeof AnakInformasiIndexRouteImport
      parentRoute: typeof AnakRoute
    }
    '/admin/warga-emas/': {
      id: '/admin/warga-emas/'
      path: '/warga-emas'
      fullPath: '/admin/warga-emas/'
      preLoaderRoute: typeof AdminWargaEmasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staf/rekod/$parentId': {
      id: '/staf/rekod/$parentId'
      path: '/rekod/$parentId'
      fullPath: '/staf/rekod/$parentId'
      preLoaderRoute: typeof StafRekodParentIdRouteImport
      parentRoute: typeof StafRoute
    }
    '/anak/perkembangan/$parentId': {
      id: '/anak/perkembangan/$parentId'
      path: '/perkembangan/$parentId'
      fullPath: '/anak/perkembangan/$parentId'
      preLoaderRoute: typeof AnakPerkembanganParentIdRouteImport
      parentRoute: typeof AnakRoute
    }
    '/anak/informasi/$id': {
      id: '/anak/informasi/$id'
      path: '/informasi/$id'
      fullPath: '/anak/informasi/$id'
      preLoaderRoute: typeof AnakInformasiIdRouteImport
      parentRoute: typeof AnakRoute
    }
    '/admin/warga-emas/baru': {
      id: '/admin/warga-emas/baru'
      path: '/warga-emas/baru'
      fullPath: '/admin/warga-emas/baru'
      preLoaderRoute: typeof AdminWargaEmasBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/warga-emas/$parentId': {
      id: '/admin/warga-emas/$parentId'
      path: '/warga-emas/$parentId'
      fullPath: '/admin/warga-emas/$parentId'
      preLoaderRoute: typeof AdminWargaEmasParentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rekod-penjagaan/$bookingId': {
      id: '/admin/rekod-penjagaan/$bookingId'
      path: '/rekod-penjagaan/$bookingId'
      fullPath: '/admin/rekod-penjagaan/$bookingId'
      preLoaderRoute: typeof AdminRekodPenjagaanBookingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rekod-harian/$recordId': {
      id: '/admin/rekod-harian/$recordId'
      path: '/rekod-harian/$recordId'
      fullPath: '/admin/rekod-harian/$recordId'
      preLoaderRoute: typeof AdminRekodHarianRecordIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staf/tracker/$parentId/': {
      id: '/staf/tracker/$parentId/'
      path: '/tracker/$parentId'
      fullPath: '/staf/tracker/$parentId/'
      preLoaderRoute: typeof StafTrackerParentIdIndexRouteImport
      parentRoute: typeof StafRoute
    }
    '/staf/tracker/$parentId/vital': {
      id: '/staf/tracker/$parentId/vital'
      path: '/tracker/$parentId/vital'
      fullPath: '/staf/tracker/$parentId/vital'
      preLoaderRoute: typeof StafTrackerParentIdVitalRouteImport
      parentRoute: typeof StafRoute
    }
    '/staf/tracker/$parentId/ubat': {
      id: '/staf/tracker/$parentId/ubat'
      path: '/tracker/$parentId/ubat'
      fullPath: '/staf/tracker/$parentId/ubat'
      preLoaderRoute: typeof StafTrackerParentIdUbatRouteImport
      parentRoute: typeof StafRoute
    }
    '/staf/tracker/$parentId/makanan': {
      id: '/staf/tracker/$parentId/makanan'
      path: '/tracker/$parentId/makanan'
      fullPath: '/staf/tracker/$parentId/makanan'
      preLoaderRoute: typeof StafTrackerParentIdMakananRouteImport
      parentRoute: typeof StafRoute
    }
    '/staf/tracker/$parentId/aktiviti': {
      id: '/staf/tracker/$parentId/aktiviti'
      path: '/tracker/$parentId/aktiviti'
      fullPath: '/staf/tracker/$parentId/aktiviti'
      preLoaderRoute: typeof StafTrackerParentIdAktivitiRouteImport
      parentRoute: typeof StafRoute
    }
    '/staf/tracker/$parentId/sejarah/$recordId': {
      id: '/staf/tracker/$parentId/sejarah/$recordId'
      path: '/tracker/$parentId/sejarah/$recordId'
      fullPath: '/staf/tracker/$parentId/sejarah/$recordId'
      preLoaderRoute: typeof StafTrackerParentIdSejarahRecordIdRouteImport
      parentRoute: typeof StafRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArtikelRoute: typeof AdminArtikelRoute
  AdminServisRoute: typeof AdminServisRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTrackerRoute: typeof AdminTrackerRoute
  AdminVideoRoute: typeof AdminVideoRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRekodHarianRecordIdRoute: typeof AdminRekodHarianRecordIdRoute
  AdminRekodPenjagaanBookingIdRoute: typeof AdminRekodPenjagaanBookingIdRoute
  AdminWargaEmasParentIdRoute: typeof AdminWargaEmasParentIdRoute
  AdminWargaEmasBaruRoute: typeof AdminWargaEmasBaruRoute
  AdminWargaEmasIndexRoute: typeof AdminWargaEmasIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtikelRoute: AdminArtikelRoute,
  AdminServisRoute: AdminServisRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTrackerRoute: AdminTrackerRoute,
  AdminVideoRoute: AdminVideoRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRekodHarianRecordIdRoute: AdminRekodHarianRecordIdRoute,
  AdminRekodPenjagaanBookingIdRoute: AdminRekodPenjagaanBookingIdRoute,
  AdminWargaEmasParentIdRoute: AdminWargaEmasParentIdRoute,
  AdminWargaEmasBaruRoute: AdminWargaEmasBaruRoute,
  AdminWargaEmasIndexRoute: AdminWargaEmasIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AnakRouteChildren {
  AnakDaftarWargaRoute: typeof AnakDaftarWargaRoute
  AnakServiceRoute: typeof AnakServiceRoute
  AnakIndexRoute: typeof AnakIndexRoute
  AnakInformasiIdRoute: typeof AnakInformasiIdRoute
  AnakPerkembanganParentIdRoute: typeof AnakPerkembanganParentIdRoute
  AnakInformasiIndexRoute: typeof AnakInformasiIndexRoute
  AnakPerkembanganIndexRoute: typeof AnakPerkembanganIndexRoute
}

const AnakRouteChildren: AnakRouteChildren = {
  AnakDaftarWargaRoute: AnakDaftarWargaRoute,
  AnakServiceRoute: AnakServiceRoute,
  AnakIndexRoute: AnakIndexRoute,
  AnakInformasiIdRoute: AnakInformasiIdRoute,
  AnakPerkembanganParentIdRoute: AnakPerkembanganParentIdRoute,
  AnakInformasiIndexRoute: AnakInformasiIndexRoute,
  AnakPerkembanganIndexRoute: AnakPerkembanganIndexRoute,
}

const AnakRouteWithChildren = AnakRoute._addFileChildren(AnakRouteChildren)

interface StafRouteChildren {
  StafWargaEmasRoute: typeof StafWargaEmasRoute
  StafIndexRoute: typeof StafIndexRoute
  StafRekodParentIdRoute: typeof StafRekodParentIdRoute
  StafRekodIndexRoute: typeof StafRekodIndexRoute
  StafTrackerParentIdAktivitiRoute: typeof StafTrackerParentIdAktivitiRoute
  StafTrackerParentIdMakananRoute: typeof StafTrackerParentIdMakananRoute
  StafTrackerParentIdUbatRoute: typeof StafTrackerParentIdUbatRoute
  StafTrackerParentIdVitalRoute: typeof StafTrackerParentIdVitalRoute
  StafTrackerParentIdIndexRoute: typeof StafTrackerParentIdIndexRoute
  StafTrackerParentIdSejarahRecordIdRoute: typeof StafTrackerParentIdSejarahRecordIdRoute
}

const StafRouteChildren: StafRouteChildren = {
  StafWargaEmasRoute: StafWargaEmasRoute,
  StafIndexRoute: StafIndexRoute,
  StafRekodParentIdRoute: StafRekodParentIdRoute,
  StafRekodIndexRoute: StafRekodIndexRoute,
  StafTrackerParentIdAktivitiRoute: StafTrackerParentIdAktivitiRoute,
  StafTrackerParentIdMakananRoute: StafTrackerParentIdMakananRoute,
  StafTrackerParentIdUbatRoute: StafTrackerParentIdUbatRoute,
  StafTrackerParentIdVitalRoute: StafTrackerParentIdVitalRoute,
  StafTrackerParentIdIndexRoute: StafTrackerParentIdIndexRoute,
  StafTrackerParentIdSejarahRecordIdRoute:
    StafTrackerParentIdSejarahRecordIdRoute,
}

const StafRouteWithChildren = StafRoute._addFileChildren(StafRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnakRoute: AnakRouteWithChildren,
  DaftarAnakRoute: DaftarAnakRoute,
  DaftarStaffRoute: DaftarStaffRoute,
  LoginRoute: LoginRoute,
  StafRoute: StafRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
